Upgraded vscode dependencies
I did this while debugging an issue I was having; unfortunately it didn't help, but at least it shouldn't make things worse (and moving onto later versions is usually a good thing).

This should be tested by someone else than me; I get errors like below both before and after this change, so it's hard for me to verify that it's fully working. But at least it builds.

```
Uncaught Exception:  Error: Header must provide a Content-Length property.
Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/Users/per/git/rls_vscode/node_modules/vscode-jsonrpc/lib/messageReader.js:179:27)
    at Socket.<anonymous> (/Users/per/git/rls_vscode/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```